### PR TITLE
feat: enable indexing for Haitian News

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Did a test deploy of this and everything seems to be working with the new Haitian News instance and the `news-ht` index on Algolia.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
This is okay to merge while the instance is still private?

**Comment by scissorsneedfoodtoo** [comment]
Hey @naomi-lgbt, yes, this should be fine to merge while the instance is still private. The webhooks are on the Ghost side of things, and will ensure that any published articles are indexed in Algolia, even if the site is still private and we're not building the final Jamstack version.

**Review by naomi-lgbt — APPROVED** [review]
Works for me.

**Comment by scissorsneedfoodtoo** [comment]
Awesome. Thanks for taking a look at this, @naomi-lgbt. I'll go ahead and deploy the changes now.

**Pull request merged**
